### ISSUE TITLE
Warning if No Icon is Set

### ISSUE THREAD

**Issue by dshanske** [dcooney/wordpress-plugin-installer#4]
You use '1x' in the icon settings. But if there is no icon set, it should be 'default'.

**Comment by dcooney** [comment]
5 years later but this was just fixed in the 1.0.1 release 🥇 
https://github.com/dcooney/wordpress-plugin-installer/releases/tag/1.0.1

https://github.com/dcooney/wordpress-plugin-installer/blob/main/class-connekt-plugin-installer.php#L124-L128
