### ISSUE TITLE
Using this class outside of the plugins directory

### ISSUE THREAD

**Issue by digitalbread** [dcooney/wordpress-plugin-installer#5]
Hi Darren,
Thank you for this class, I'm using it in a plugin and have had it setup for Recommended plugins from the WordPress.org repo which was working great. I then tried to set it up for Required Extensions and placed the extensions (zipped plugins) in a sub folder of the plugin called extensions changed the `define('CNKT_INSTALLER_PATH', plugins_url().'/my-plugin/extensions/')` and for some reason it's only showing extensions that were uploaded via plugins and activated. See screenshot.
https://www.screencast.com/t/Byxmz2whapst
Thanks for your help.
Russ

**Comment by dcooney** [comment]
@digitalbread The class is only for plugins hosted on the WP.org repository.

**Comment by digitalbread** [comment]
@dcooney ok thanks, sorry I totally misunderstood the outside of repo setting. I was able to use https://github.com/TGMPA/TGM-Plugin-Activation for local required plugins. Thanks for your response and the wordpress-plugni-installer. Take care man.
