### ISSUE TITLE
Limit assets loading js/css to specific pages

### ISSUE THREAD

**Issue by cfoellmann** [dcooney/wordpress-plugin-installer#6]
You should limit the enqueue of the js and css files to specific admin pages.
I would love to send you a PR for this to fix it in "Instant Images".
BUT I don't know how you want to implement it. You need to hand over the hooks of the pages that should load the assets.

**Comment by dcooney** [comment]
5 years late but This was just fixed in 1.0.1 release. https://github.com/dcooney/wordpress-plugin-installer/releases/tag/1.0.1

😏
